#!/bin/bash
# cross-pi-wxwidgets.sh
# Cross-compile wxWidgets for Raspberry PI, using toolchain generated by cross-pi-buildroot.sh
#
# exclude some rarely used stuff
# change =no to =yes or omit =no to include in build ( we have removed --with-opengl from ENABLE)
XTIFF="--with-libtiff=no"
XJPEG="--with-libjpeg=yes"
ODBC="--with-odbc=no"

# put here things to explicitely enable  
ENABLE="--with-gtk --enable-unicode --enable-dnd --enable-dataobj --enable-graphics-ctx"

# put here things to explicitely disable
DISABLE="--enable-shared=no --enable-iff=no --enable-tga=no --enable-pcx=no --enable-mediactrl=no --enable-dialupman=no --with-libmspack=no"

# argument can be D for debug version
if [ "$1" = "D" ] ; 
then
  DEB="--enable-debug"
else
  DEB="--enable-debug=no"
fi

# Download wxwidgets and build in a temporary, disposable folde
wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.4/wxWidgets-3.0.4.tar.bz2 -P /tmp/build_wxwidgets

# Extract the download package
pushd /tmp/build_wxwidgets/ > /dev/null 
tar -xvf ./wxWidgets-3.0.4.tar.bz2 
pushd wxWidgets-3.0.4/ > /dev/null 

# create a build folder for Raspberry PI
mkdir buildrpi
pushd buildrpi > /dev/null 

# make sure the buildroot toolchain is first in PATH so we find the correct cross-compiler 
export PATH=$HOME/cross-pi/buildroot/output/host/usr/bin:$PATH

# this is where cross-compled wxWidgets will be installed
CFG_PREFIX="$HOME/cross-pi/3rdparty/wxwidgets"

# the target host system is Raspberry PI, a.k.a. arm-linux
# Actually this is armV7
CFG_HOST="arm-linux"

# Run the wxwidgets configure script
../configure --host=${CFG_HOST} --prefix=${CFG_PREFIX}  ${ENABLE} ${DISABLE} ${XJPEG} ${XTIFF} ${ODBC} ${DEB}
if [ $? != 0 ]; then exit -1 ; fi

# build the libraries
make
if [ $? != 0 ]; then exit -1 ; fi

# install to the CFG_PREFIX target folder
make install
if [ $? != 0 ]; then exit -1 ; fi

ldconfig
if [ $? != 0 ]; then exit -1 ; fi

# back up directory tree
popd > /dev/null
popd > /dev/null
popd > /dev/null

